=== bradledbetter/beerschema/yeasts/yeasts.schema.json
{
    "$id": "https://api-menuviz.net/fermentables.schema.json",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "BeerJSONModel",
    "description": "A simple schema to describe something yeast can ferment.",
    "type": "object",
    "properties": {
        "id": {
            "type": "string"
        },
        "label": {
            "type": "string"
        },
        "description": {
            "type": "string"
        },
        "manufacturer": {
            "type": "string"
        },
        "manufacturerCode": {
            "type": "string"
        },
        "flocculation": {
            "type": "string",
            "enum": [
                "low",
                "medium",
                "high",
                "very high"
            ]
        },
        "alcoholTolerance": {
            "type": "string",
            "enum": [
                "Low",
                "Medium",
                "Medium-High",
                "High",
                "Very High"
            ]
        },
        "minTemperature": {
            "type": "number"
        },
        "maxTemperature": {
            "type": "number"
        },
        "minAttenuation": {
            "type": "number"
        },
        "maxAttenuation": {
            "type": "number"
        },
        "substitutions": {
            "type": "array",
            "items": {
                "type": "string"
            }
        }
    },
    "required": [
        "label",
        "manufacturer",
        "manufacturerCode"
    ]
}

=== bradledbetter/beerschema/yeasts/mocks/yeasts.json
[
{
    "id": "66ee4250-e5fc-11e8-86e3-452a7a8ac81c",
    "label": "California Ale",
    "description": "This strain was the first yeast strain produced by White Labs in 1995. Famous for its clean flavors and hardy fermentations. Known for its use in hoppy beers, it accentuates hop flavors and aromas and attenuates well, even for high gravity beers. This strain has the ability to be used in almost any style of ale ranging from IPA to porter and even koÌˆlsch, which makes it a great all-around house strain.",
    "manufacturer": "White Labs",
    "manufacturerCode": "WLP001",
    "flocculation": "medium",
    "alcoholTolerance": "High",
    "minTemperature": 68,
    "maxTemperature": 73,
    "minAttenuation": 73,
    "maxAttenuation": 80,
    "substitutions": []
},
{
    "id": "7cbeabb0-e5fc-11e8-86e3-452a7a8ac81c",
    "label": "American Ale",
    "description": "Very clean, crisp flavor characteristics with low fruitness and mild ester production. A very versatile yeast for styles that desire dominant malt and hop character. This strain makes a wonderful 'House' strain. Mild citrus notes develop with cooler 60-66F (15-19C) fermentations. Normally requires filtration for bright beers.",
    "manufacturer": "Wyeast",
    "manufacturerCode": "1056",
    "flocculation": "medium",
    "alcoholTolerance": "High",
    "minTemperature": 60,
    "maxTemperature": 72,
    "minAttenuation": 73,
    "maxAttenuation": 77,
    "substitutions": []
}
]
