=== bradledbetter/beerschema/hops/hops.schema.json
{
    "$id": "https://api-menuviz.net/hops.schema.json",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "BeerJSONModel",
    "description": "A simple schema to describe a hop varietal",
    "type": "object",
    "properties": {
        "id": {
            "type": "string"
        },
        "label": {
            "type": "string"
        },
        "aka": {
            "type": "array"
        },
        "countryOfOrigin": {
            "type": "object",
            "properties": {
                "label": {
                    "type": "string"
                },
                "twoChar": {
                    "type": "string"
                },
                "threeChar": {
                    "type": "string"
                }
            }
        },
        "description": {
            "type": "string"
        },
        "form": {
            "type": "string"
        },
        "cropYear": {
            "type": "integer"
        },
        "alpha": {
            "type": "number"
        },
        "beta": {
            "type": "number"
        },
        "humulene": {
            "type": "number"
        },
        "caryophyllene": {
            "type": "number"
        },
        "myrcene": {
            "type": "number"
        },
        "cohumulone": {
            "type": "number"
        },
        "totalOil": {
            "type": "number"
        }
    },
    "required": [
        "label"
    ]
}

=== bradledbetter/beerschema/hops/mocks/hops.json
[
    {
        "countryOfOrigin": {
            "twoChar": "GB",
            "label": "Great Britain",
            "threeChar": "GBR"
        },
        "description": "Aromas of lavender, spice, honey, thyme, earthy flavors",
        "id": "ecb21890-d917-11e8-a50c-fd28cb3bfd5b",
        "label": "East Kent Golding",
        "aka": [
            "Kent Golding",
            "EKG",
            "Canterbury Golding"
        ]
    },
    {
        "countryOfOrigin": {
            "twoChar": "AU",
            "label": "Australia",
            "threeChar": "AUS"
        },
        "description": "Tropical fruit, pine, herbs",
        "id": "dcbf07f0-d88f-11e8-98ba-e35f1f7aa8a8",
        "label": "Vic Secret",
        "aka": [
            "Victoria",
            "Victoria’s Secret",
            "Victoria Secret"
        ]
    },
    {
        "countryOfOrigin": {
            "twoChar": "US",
            "label": "United States",
            "threeChar": "USA"
        },
        "id": "470b1340-ce6f-11e8-825b-5fbf22fdb82a",
        "description": "Grapefruit",
        "label": "Citra",
        "aka": [
            "Citra® Brand HBC 394 cv",
            "HBC394"
        ]
    },
    {
        "countryOfOrigin": {
            "twoChar": "US",
            "label": "United States",
            "threeChar": "USA"
        },
        "description": "Aroma variety with floral, blueberry, tangerine, papaya, rose blossoms, grass, earthy & bubble gum notes.",
        "id": "843e4740-d082-11e8-b04c-a55c5f6253ec",
        "label": "Mosaic",
        "aka": [
            "HBC369"
        ]
    }
]
